#!/bin/bash


nor=20	# number of runs


# Uncomment/modify appropriate lines in the code below as per your requirement
for (( run=1 ; run<nor+1 ; run=${run}+1 )) do
	if (($run < 21)) 
	then
		nohup python3 -m progsys.progsys --run $run --parameters parameters/Zhang.yml &
	
	elif (($run < 41))
	then
		nohup python3 -m progsys.progsys --run $run --parameters parameters/Forst.yml &
		
	else
		nohup python3 -m progsys.progsys --run $run --parameters parameters/extended.yml &
	fi

done
