#!/bin/bash


nor=300		# number of runs


# Uncomment/modify appropriate lines in the code below as per your requirement
for (( run=1 ; run<nor+1 ; run=${run}+1 )) do
	if (($run < 76))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 9 --prob_context 0.05 --prob_mutation 0.08 --maxdepth 17 --experiment_name 'dumps/Smallest/IRACE_1/' --parameters parameters/standard.yml  &
	elif (($run < 151))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 6 --prob_context 0.05 --prob_mutation 0.09 --maxdepth 20 --experiment_name 'dumps/Smallest/IRACE_2/' --parameters parameters/standard.yml  &
	elif (($run < 226))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 7 --prob_context 0.06 --prob_mutation 0.09 --maxdepth 19 --experiment_name 'dumps/Smallest/IRACE_3/' --parameters parameters/standard.yml  &
	else
		nohup python3 -m progsys.progsys --run $run --elitism 6 --prob_context 0.07 --prob_mutation 0.09 --maxdepth 20 --experiment_name 'dumps/Smallest/IRACE_4/' --parameters parameters/standard.yml  &

	fi

done
