#!/bin/bash


nor=100		# number of runs


# Uncomment/modify appropriate lines in the code below as per your requirement
for (( run=1 ; run<nor+1 ; run=${run}+1 )) do
	if (($run < 51))
	then
		nohup python3 -m progsys.LastIndexofZero --run $run --parameters parameters/LastIndexofZero.yml  &
	elif (($run < 101))
	then
		nohup python3 -m progsys.NegativeToZero --run $run --parameters parameters/NegativeToZero.yml  &
	elif (($run < 151))
	then
		nohup python3 -m progsys.MirrorImage --run $run --parameters parameters/MirrorImage.yml  &
	elif (($run < 401))
	then
		nohup python3 -m progsys.DoubleLetters --run $run --parameters parameters/DoubleLetters.yml  &
	elif (($run < 501))
	then
		nohup python3 -m progsys.EvenSquares --run $run --parameters parameters/EvenSquares.yml  &
	elif (($run < 601))
	then
		nohup python3 -m progsys.ForLoopIndex --run $run --parameters parameters/ForLoopIndex.yml  &
	elif (($run < 701))
	then
		nohup python3 -m progsys.Grade --run $run --parameters parameters/Grade.yml  &
	elif (($run < 801))
	then
		nohup python3 -m progsys.LastIndexofZero --run $run --parameters parameters/LastIndexofZero.yml  &
	elif (($run < 901))
	then
		nohup python3 -m progsys.MirrorImage --run $run --parameters parameters/MirrorImage.yml  &
	elif (($run < 1001))
	then
		nohup python3 -m progsys.NegativeToZero --run $run --parameters parameters/NegativeToZero.yml  &
	elif (($run < 1101))
	then
		nohup python3 -m progsys.NumberIO --run $run --parameters parameters/NumberIO.yml  &
	elif (($run < 1201))
	then
		nohup python3 -m progsys.PigLatin --run $run --parameters parameters/PigLatin.yml  &
	else
		nohup python3 -m progsys.SmallOrLarge --run $run --parameters parameters/SmallOrLarge.yml  &

	fi

done
