#!/bin/bash


nor=630		# number of runs


# Uncomment/modify appropriate lines in the code below as per your requirement
for (( run=1 ; run<nor+1 ; run=${run}+1 )) do
	if (($run < 31))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 2 --prob_mutation 0.10 --mutation_strategy 'Shrink' --prob_context 0.2 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 61))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 4 --prob_mutation 0.05 --prob_context 0.2 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 91))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 4 --prob_mutation 0.10 --mutation_strategy 'Shrink' --prob_context 0.2 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 121))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 4 --prob_mutation 0.15 --mutation_strategy 'Shrink' --prob_context 0.2 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 151))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 5 --prob_mutation 0.10 --prob_context 0.2 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 181))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 5 --prob_mutation 0.10 --mutation_strategy 'Shrink' --prob_context 0.2 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 211))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 5 --prob_mutation 0.15 --mutation_strategy 'Shrink' --prob_context 0.2 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 241))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 1 --prob_mutation 0.1 --mutation_strategy 'Shrink' --prob_context 0.1 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 271))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 1 --prob_mutation 0.05 --mutation_strategy 'Shrink' --prob_context 0.1 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 301))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 2 --prob_mutation 0.05 --prob_context 0.1 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 331))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 3 --prob_mutation 0.10 --mutation_strategy 'Shrink' --prob_context 0.1 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 361))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 3 --prob_mutation 0.05 --mutation_strategy 'Shrink' --prob_context 0.1 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 391))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 4 --prob_mutation 0.05 --prob_context 0.1 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 421))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 1 --prob_mutation 0.05 --mutation_strategy 'Shrink' --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 451))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 3 --prob_mutation 0.1 --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 481))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 3 --prob_mutation 0.10 --mutation_strategy 'Shrink' --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 511))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 3 --prob_mutation 0.15 --mutation_strategy 'Shrink' --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 541))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 3 --prob_mutation 0.05 --mutation_strategy 'Shrink' --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 571))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 4 --prob_mutation 0.10 --mutation_strategy 'Shrink' --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	elif (($run < 601))
	then
		nohup python3 -m progsys.progsys --run $run --elitism 4 --prob_mutation 0.05 --mutation_strategy 'Shrink' --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &
	else
		nohup python3 -m progsys.progsys --run $run --elitism 5 --prob_mutation 0.05 --prob_context 0.05 --experiment_name 'dumps/MedianMoreRuns/' --parameters parameters/standard.yml  &

	fi

done
